### ISSUE TITLE
Update and requests

### ISSUE THREAD

**Issue by Frankiemouse** [balg/circleOclock#8]
It would be awesome if you could update this clock face to work with the versa 3. And if possible add an option to display the steps, floors, heart rate, and battery level, or to have them all off.

**Comment by balg** [comment]
Awesome! Yours is the first request in this repo! :)

The good news is that i currently own a versa 3 so there are at least the 2 of us who wait for the update. I will update this issue when i'll have the time to work in this.

**Comment by balg** [comment]
@Frankiemouse I have submitted a new build for review but maybe you can access it via direct link: https://gallery.fitbit.com/details/e05b07b3-cd23-493b-b042-16356c965c18

**Comment by balg** [comment]
I close this issue now as the requested feature is available in the new version of https://github.com/balg/circleOclockOS5
